---
title: "COVID19"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(countrycode)
library(plotly)
library(dplyr)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Data Input

```{r}
covid_df = readxl::read_xlsx('MortalityDataWHR2021C2.xlsx') %>% 
  drop_na() %>% 
  janitor::clean_names() %>% 
  mutate(
    death_change = all_cause_death_count_2020 - all_cause_death_count_2019) 

covid_longer = covid_df %>% 
  pivot_longer(
    all_cause_death_count_2017:all_cause_death_count_2017,
    names_to = "year",
    names_prefix = "all_cause_death_count_",
    values_to = "death"
  ) %>% 
  mutate(year = as.numeric(year))

happy_df = readxl::read_xls('DataPanelWHR2021C2.xls') %>% 
  janitor::clean_names() %>% 
  select(1:3) %>% 
  subset(
    country_name != "Kosovo" & country_name != "Somaliland region"
  ) %>% 
  mutate(
    country_code = countrycode(country_name, "country.name", "iso3c")
  ) %>% 
  relocate(country_code) %>% 
  mutate(
    country_continent = countrycode(country_name, "country.name", "continent")
  ) %>% 
  relocate(country_continent) %>% 
  subset(year %in% c(2017,2018,2019,2020))
```


```{r}
covid_death_rate = covid_df %>% 
  plot_ly(x = ~country_name, 
         y = ~covid_19_deaths_per_100_000_population_in_2020,
         type = "bar", colors = "viridis")

covid_death_rate
```

```{r}
happy_wider = 
  happy_df %>% 
  pivot_wider(
    names_from = year,
    values_from = life_ladder,
    names_glue = "life_ladder_{year}"
  ) %>% 
  drop_na() %>% 
  mutate(happy_change = life_ladder_2020 - life_ladder_2019) 

covid_happy_trend = 
  left_join(covid_df, happy_wider, by = "country_name") %>% 
  drop_na()

covid_happy_trend %>% 
  ggplot(aes(x = covid_19_deaths_per_100_000_population_in_2020, 
             y = happy_change)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
covid_happy_trend_fc = 
  covid_happy_trend %>% 
  mutate(country_continent = factor(country_continent))

model = lm(happy_change ~ covid_19_deaths_per_100_000_population_in_2020 + country_continent, data = covid_happy_trend_fc)
summary(model)
```

```{r}
covid_happy_trend %>% 
  ggplot(aes(x = covid_19_deaths_per_100_000_population_in_2020, 
             y = death_change)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
model = lm(death_change ~ covid_19_deaths_per_100_000_population_in_2020, data = covid_happy_trend_fc)
summary(model)
```

```{r}
covid_happy = 
  left_join(covid_longer, happy_df, by = c("country_name", "year")) %>% 
  drop_na() %>% 
  group_by(country_name) %>% 
  filter(n() == 4)
```





