---
title: "Data"
output: 
  html_document:
    toc: true
    toc_float: true
---
## Data Sources

## Data Processing and Cleaning

## Data Description

* `country_code`: country name in iso3 code format.
* `country_name`: country name in country name (English) format.
* `year`: the year of the measurements on that row.
* `life_ladder`: happiness score.
* `log_gdp_per_capita`: the statistics of GDP per capita pf each country.
* `social_support`: national average of social support data.
* `healthy_life_expectancy_at_birth`: healthy life expectancy at birth
* `freedom_to_make_life_choices`: national average freedom to make life choices. 
* `generosity`: the residual of regressing national average of donation on GDP per capita.
* `perceptions_of_corruption`: national average of corrpution perceptions score.
* `positive_affect`: average of three positive affect measures in GWP: happiness, laugh and enjoyment.
* `negative_affect`: average of three negative affect measures in GWP: worry, sadness and anger.


