---
title: "Happiness & factors"
author: "Yunlin Zhou"
date: "11/21/2021"
output: html_document
---

```{r}
library(tidyverse)
library(plotly)
```

```{r}
happy_df = readxl::read_xls('DataPanelWHR2021C2.xls') %>% 
  janitor::clean_names()

```

```{r}
happy_df_fac = happy_df%>%
  filter(year < 2019)

round2 = function(x){
  if(is.numeric(x))
  x= round(x, digits = 2)
  return(x)
}

happy_df_fac = map_dfc(happy_df_fac, round2)
```

```{r}
plot_happy = function(A,B,name){
happy_B = bind_cols(A=A,B=B,country_name = happy_df_fac$country_name,
                    year = happy_df_fac$year) %>% 
  filter(!is.na(A))%>%
  filter(!is.na(B))%>%
  arrange(B)%>%
  mutate(
  text_label = 
  str_c("Happiness score: ", A,
        "\n",name,": ", B,
         "\nCountry: ", country_name,
         "\nYear: ", year))

fit_B = lm(A ~ B, data = happy_B)

happy_B%>%
  plot_ly(
    x = ~B,
    y = ~A,
    type = "scatter",
    mode = "markers",
    color = ~year,
    text = ~text_label,
    alpha = 0.5
  )%>%
  add_lines(x = ~B, y = predict(fit_B), color = NULL)%>%
  layout(
    xaxis = list(title = name), yaxis = list(title = "Happiness score")
  )

}
```

```{r}
plot_log = plot_happy(A=happy_df_fac$life_ladder,B =happy_df_fac$log_gdp_per_capita, name = "log_gdp_per_capita")
plot_log

plot_social = plot_happy(A=happy_df_fac$life_ladder,B =happy_df_fac$social_support, name = "social_support")
plot_social

plot_healthy = plot_happy(A=happy_df_fac$life_ladder,B =happy_df_fac$healthy_life_expectancy_at_birth, name = "healthy_life_expectancy_at_birth")
plot_healthy

plot_freedom = plot_happy(A=happy_df_fac$life_ladder,B =happy_df_fac$freedom_to_make_life_choices, name = "freedom_to_make_life_choices")
plot_freedom

plot_generosity = plot_happy(A=happy_df_fac$life_ladder,B =happy_df_fac$generosity, name = "generosity")
plot_generosity

plot_perceptions = plot_happy(A=happy_df_fac$life_ladder,B =happy_df_fac$perceptions_of_corruption, name = "perceptions_of_corruption")
plot_perceptions

plot_positive = plot_happy(A=happy_df_fac$life_ladder,B =happy_df_fac$positive_affect, name = "positive_affect")
plot_positive

plot_negative = plot_happy(A=happy_df_fac$life_ladder,B =happy_df_fac$negative_affect, name = "negative_affect")
plot_negative

```

